create table public.interactions (
  id bigint generated by default as identity not null,
  session_id uuid not null,
  timestamp timestamp with time zone default now(),
  user_msg text not null,
  ai_msg text not null,
  ai_name text not null,
  intimacy_score numeric,
  sticker_awarded text,
  gift_given boolean default false,
  response_analysis jsonb
);

-- Add indexes for better query performance
create index interactions_session_id_idx on public.interactions (session_id);
create index interactions_timestamp_idx on public.interactions (timestamp);